apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  ports:
  - name: "5021"
    port: 5021
    targetPort: 5021
    nodePort: 30021
    protocol: TCP
  selector:
    service: udaconnect-location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-producer
  template:
    metadata:
      labels:
        service: udaconnect-location-producer
    spec:
      containers:
      - image: borart22/udaconnect-location-producer:latest
        name: udaconnect-location-producer
        imagePullPolicy: Always
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_HOST
        - name: KAFKA_TOPIC_LOCATION
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC_LOCATION
      restartPolicy: Always
