apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-consumer
  name: udaconnect-location-consumer
spec:
  ports:
  - name: "5022"
    port: 5022
    targetPort: 5022
    nodePort: 30022
  selector:
    service: udaconnect-location-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-consumer
  name: udaconnect-location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-consumer
  template:
    metadata:
      labels:
        service: udaconnect-location-consumer
    spec:
      containers:
      - image: borart22/udaconnect-location-consumer:latest
        name: udaconnect-location-consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_HOST
        - name: KAFKA_TOPIC_LOCATION
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC_LOCATION
      restartPolicy: Always 