name: UdaConnect - Package with Docker

on:
  push:
    branches: [ never]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/api_v1
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-api:latest          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/frontend
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-app:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/location_api
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-location-api:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/location-producer
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-location-producer:latest 
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/location-consumer
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-location-consumer:latest 
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/person-api
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-person-api:latest           
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/connection-api
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/udaconnect-connection-api:latest